Listas

In [ ]:
listaMarcaAutos = ["Chevrolet", "Toyota", "Nissan", "Mazda"]
listaMarcaMotos = ["Honda", "Yamaha", "Suzuki", "Kawasaki"]
print(listaMarcaAutos)
print(listaMarcaMotos)
type(listaMarcaAutos)

for marca in listaMarcaAutos:
  print(marca)

['Chevrolet', 'Toyota', 'Nissan', 'Mazda']
['Honda', 'Yamaha', 'Suzuki', 'Kawasaki']
Chevrolet
Toyota
Nissan
Mazda

Tuplas

In [ ]:
tuplaDeportes =("Futbol", "Basketball", "Tenis", "Voleibol")
tuplaDeportesMotor = ("F1", "Moto GP", "Nascar", "Formula e")
print(tuplaDeportes)
print(tuplaDeportesMotor)
type(tuplaDeportes)
i=0
while (i < len(tuplaDeportes)):
  print(tuplaDeportes[i])
  i = i + 1

('Futbol', 'Basketball', 'Tenis', 'Voleibol')
('F1', 'Moto GP', 'Nascar', 'Formula e')
Futbol
Basketball
Tenis
Voleibol

Conjuntos

In [ ]:
conjuntoEquiposFutbol = {"Barcelona", "Real Madrid", "Atletico Madrid", "Sevilla", "Villareal"}
type(conjuntoEquiposFutbol)
print(conjuntoEquiposFutbol)
for equipo in conjuntoEquiposFutbol:
  print(equipo)

{'Real Madrid', 'Atletico Madrid', 'Sevilla', 'Barcelona', 'Villareal'}
Real Madrid
Atletico Madrid
Sevilla
Barcelona
Villareal

Operaciones entre conjuntos

In [ ]:
#Union
conjunto1 = {1,2,3,4,5}
conjunto2 = {6,7,8,9,10}
conjuntoUnion = conjunto1.union(conjunto2)
print(conjuntoUnion)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [ ]:
#Interseccion
conjunto3 = {1,2,3,4,5}
conjunto4 = {3,4,5,6,7}
conjuntoInterseccion = conjunto3.intersection(conjunto4)
print(conjuntoInterseccion)

{3, 4, 5}

In [ ]:
#Diferencia
conjunto5 = {1,2,3,4,5}
conjunto6 = {3,4,5,6,7,8,9}
conjuntoDiferencia5 = conjunto5.difference(conjunto6)
conjuntoDiferencia6 = conjunto6.difference(conjunto5)
print(conjuntoDiferencia5)
print(conjuntoDiferencia6)

{1, 2}
{8, 9, 6, 7}

In [ ]:
#Diferencia Simetrica
conjunto7 = {1,2,3,4,5}
conjunto8 = {3,4,5,6,7,8,9}
conjuntoDiferenciaSimetrica = conjunto7.symmetric_difference(conjunto8)
print(conjuntoDiferenciaSimetrica)

{1, 2, 6, 7, 8, 9}

In [ ]:
#Complemento
conjunto9 = {1,2,3,4,5}
conjunto10 = {3,4,5,6,7,8,9}
conjuntoComplemento = conjunto9.difference(conjunto10)
print(conjuntoComplemento)

{1, 2}

Diccionario

In [ ]:
futbolistasFCB = {"Portero":"TerStegen", "Defensa":"Cubarsi", "MedioCampista":"Pedri", "Delantero":"LamineYamal"}
print(futbolistasFCB)
print(futbolistasFCB["Portero"])
print(futbolistasFCB["MedioCampista"])
print(futbolistasFCB.keys())
print(futbolistasFCB.values())

for posicion, nombre in futbolistasFCB.items():
  print("Posicion: " + posicion +", Nombre: " + nombre)

{'Portero': 'TerStegen', 'Defensa': 'Cubarsi', 'MedioCampista': 'Pedri', 'Delantero': 'LamineYamal'}
TerStegen
Pedri
dict_keys(['Portero', 'Defensa', 'MedioCampista', 'Delantero'])
dict_values(['TerStegen', 'Cubarsi', 'Pedri', 'LamineYamal'])
Posicion: Portero, Nombre: TerStegen
Posicion: Defensa, Nombre: Cubarsi
Posicion: MedioCampista, Nombre: Pedri
Posicion: Delantero, Nombre: LamineYamal

Convertir un diccionario en un data frame

In [ ]:
#Importamos pandas
import pandas as pd
datosPersonas = {
    "Nombre": ["Juan", "Maria", "Pedro", "Ana"],
    "Edad": [25, 30, 35, 40],
    "Ciudad": ["Popayan", "Pasto", "Cali", "Bogota"]
}
type(datosPersonas)

dict

In [ ]:
df = pd.DataFrame(datosPersonas)
print(df)
type(df)

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1  Maria    30  Barcelona
2  Pedro    35   Valencia
3    Ana    40    Sevilla

pandas.core.frame.DataFrame